#!/usr/bin/env python3
"""Append xengsort contamination fractions to the study metadata.

Intermediate step between xengsort (host/graft read sorting) and the RUVSeq
contamination-adjustment analysis. Reads the per-sample xengsort classify logs
and appends graft_pct / host_pct / both_pct columns to the design metadata --
so those fractions are derived from the pipeline output rather than hand-typed.

xengsort 2.1.0 writes one log per sample to <xengsort-dir>/<sample>.txt. Each
log contains a machine-readable counts block under "## Classification
Statistics":

    ## Classification Statistics

    ```
    prefix  host    graft   ambiguous       both    neither
    IL64B   90003153        314037  175597  4546256 1124564
    ```

This script parses that header + counts row (whitespace/tab separated, column
order taken from the header so it is robust to reordering) and computes each
class percentage as count / total * 100, where total is the sum of all five
classes. That reproduces the percentages xengsort prints in its pipe-table
block (e.g. IL64B graft = 314037 / 96163607 = 0.33%).

Two outputs:

  1. (default) the analysis metadata CSV: metadata_base.csv (sample,
     Classification for the 9 in-vivo samples) + appended fractions ->
     metadata_full.csv. Consumed by ruvseq_contamination_adjustment.R.

  2. (--emit-markdown) the README sample table: a descriptive cohorts file
     (sample_cohorts.csv, all 10 libraries incl. the in-vitro C2B reference)
     joined with the xengsort fractions, rendered as a GitHub markdown table.
     If the target file contains the BEGIN/END markers, the table is injected
     in place; otherwise it is written whole (use '-' for stdout). This keeps
     the README table from drifting away from the actual xengsort numbers.

Usage:
    # rebuild analysis metadata (what run_ruvseq.sh calls)
    python3 build_metadata_from_xengsort.py \
        --base ANALYSIS/metadata_base.csv \
        --xengsort-dir ANALYSIS/xengsort_out \
        --out ANALYSIS/metadata_full.csv

    # refresh the README sample table in place
    python3 build_metadata_from_xengsort.py --markdown-only \
        --cohorts ANALYSIS/sample_cohorts.csv \
        --xengsort-dir ANALYSIS/xengsort_out \
        --emit-markdown README.md
"""

import argparse
import csv
import os
import sys

# Classes xengsort 2.1.0 reports, in the order they normally appear. The parser
# does not rely on this order (it reads the header), but it defines what we
# expect to find and which fractions land in the metadata.
XENGSORT_CLASSES = ("host", "graft", "ambiguous", "both", "neither")
# Columns appended to the metadata, mapped to their xengsort class.
APPENDED = (("graft_pct", "graft"), ("host_pct", "host"), ("both_pct", "both"))

# Markers delimiting the auto-generated sample table in README.md.
MD_BEGIN = ("<!-- BEGIN sample-table: generated by "
            "ANALYSIS/build_metadata_from_xengsort.py --emit-markdown; "
            "do not edit by hand -->")
MD_END = "<!-- END sample-table -->"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def parse_xengsort_log(path):
    """Return (prefix, {class_name: int_count}) from a single xengsort log.

    Locates the counts block: a header line whose first token is 'prefix' and
    which lists the class names, followed by a data line of integer counts.
    """
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        lines = fh.read().splitlines()

    for i, line in enumerate(lines):
        tokens = line.split()
        # Header row of the TSV counts block, e.g.
        #   prefix  host  graft  ambiguous  both  neither
        if tokens and tokens[0] == "prefix" and "host" in tokens and "graft" in tokens:
            class_cols = tokens[1:]
            # The next non-empty line is the per-sample counts row.
            for data_line in lines[i + 1:]:
                data_tokens = data_line.split()
                if not data_tokens:
                    continue
                values = data_tokens[1:]  # drop the sample-name prefix
                if len(values) != len(class_cols):
                    raise ValueError(
                        f"{path}: counts row has {len(values)} values but header "
                        f"has {len(class_cols)} classes ({class_cols})")
                try:
                    counts = {cls: int(val) for cls, val in zip(class_cols, values)}
                except ValueError as exc:
                    raise ValueError(f"{path}: non-integer count in row "
                                     f"'{data_line.strip()}'") from exc
                return data_tokens[0], counts
            raise ValueError(f"{path}: found counts header but no data row after it")

    raise ValueError(f"{path}: no '## Classification Statistics' counts block found")


def percentages(counts):
    """Convert a class->count dict into class->percent (of all reads)."""
    total = sum(counts.values())
    if total == 0:
        raise ValueError("total read count is zero")
    return {cls: 100.0 * n / total for cls, n in counts.items()}


def fractions_for(sample, xengsort_dir, allow_missing=False):
    """Return class->percent for a sample, or None if missing/unparseable and
    allow_missing is set."""
    log_path = os.path.join(xengsort_dir, f"{sample}.txt")
    if not os.path.isfile(log_path):
        msg = f"{sample}: log not found ({log_path})"
        if allow_missing:
            print(f"WARNING: {msg} -- skipped")
            return None, None
        sys.exit(f"ERROR: {msg}")
    try:
        prefix, counts = parse_xengsort_log(log_path)
        missing = [c for c in XENGSORT_CLASSES if c not in counts]
        if missing:
            raise ValueError(f"missing classes {missing}")
        return prefix, counts
    except ValueError as exc:
        if allow_missing:
            print(f"WARNING: {sample}: parse failed -- {exc} -- skipped")
            return None, None
        sys.exit(f"ERROR: {sample}: parse failed -- {exc}")


def build_csv(args):
    """Append xengsort fractions to the design metadata -> args.out."""
    if not os.path.isfile(args.base):
        sys.exit(f"ERROR: base metadata not found: {args.base}")

    with open(args.base, newline="") as fh:
        reader = csv.DictReader(fh)
        base_fields = reader.fieldnames or []
        if "sample" not in base_fields or "Classification" not in base_fields:
            sys.exit("ERROR: base metadata must have 'sample' and "
                     "'Classification' columns")
        rows = list(reader)

    out_fields = list(base_fields) + [c for c, _ in APPENDED if c not in base_fields]

    print(f"Base metadata : {args.base} ({len(rows)} samples)")
    print(f"xengsort dir  : {args.xengsort_dir}")
    print("-" * 78)
    print(f"{'sample':<8} {'class':<10} " +
          "  ".join(f"{cls:>9}" for cls in XENGSORT_CLASSES) +
          "   graft%   host%   both%")

    out_rows, failures = [], []
    for row in rows:
        sample = row["sample"]
        prefix, counts = fractions_for(sample, args.xengsort_dir, args.allow_missing)
        if counts is None:
            failures.append(sample)
            continue
        if prefix != sample:
            print(f"WARNING: {sample}: log prefix is '{prefix}' (using filename "
                  f"sample name)")
        pct = percentages(counts)
        new_row = dict(row)
        for col, cls in APPENDED:
            new_row[col] = f"{pct[cls]:.2f}"
        out_rows.append(new_row)
        print(f"{sample:<8} {row['Classification']:<10} " +
              "  ".join(f"{counts[c]:>9d}" for c in XENGSORT_CLASSES) +
              f"   {pct['graft']:6.2f}  {pct['host']:6.2f}  {pct['both']:6.2f}")

    if not out_rows:
        sys.exit("ERROR: no samples were successfully processed")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=out_fields)
        writer.writeheader()
        writer.writerows(out_rows)

    print("-" * 78)
    print(f"Wrote {args.out} ({len(out_rows)} samples, "
          f"columns: {', '.join(out_fields)})")
    if failures:
        print(f"Samples skipped: {', '.join(failures)}")


def render_markdown(cohorts, xengsort_dir, allow_missing=False):
    """Render the README sample table (markdown) from a cohorts list joined
    with xengsort-derived graft/host fractions."""
    headers = ["Sample", "Cohort", "Environment", "graft %", "host %",
               "Role in analysis"]
    rows = []
    for c in cohorts:
        sample = c["sample"]
        _, counts = fractions_for(sample, xengsort_dir, allow_missing)
        if counts is None:
            continue
        pct = percentages(counts)
        rows.append([sample, c.get("cohort", ""), c.get("environment", ""),
                     f"{pct['graft']:.2f}", f"{pct['host']:.2f}",
                     c.get("role", "")])
    if not rows:
        sys.exit("ERROR: no cohort samples could be rendered")

    widths = [len(h) for h in headers]
    for r in rows:
        for i, cell in enumerate(r):
            widths[i] = max(widths[i], len(cell))

    def fmt(cells):
        return "| " + " | ".join(c.ljust(widths[i]) for i, c in enumerate(cells)) + " |"

    sep = "| " + " | ".join("-" * widths[i] for i in range(len(headers))) + " |"
    return "\n".join([fmt(headers), sep] + [fmt(r) for r in rows]) + "\n"


def emit_markdown(target, table_md):
    """Write the table to stdout ('-'), inject between README markers if the
    target file has them, or otherwise write the table as the whole file."""
    if target == "-":
        sys.stdout.write(table_md)
        return
    if os.path.isfile(target):
        with open(target, encoding="utf-8") as fh:
            content = fh.read()
        b, e = content.find(MD_BEGIN), content.find(MD_END)
        if b != -1 and e != -1 and e > b:
            line_end = content.find("\n", b) + 1   # keep the BEGIN marker line
            new = content[:line_end] + table_md + content[e:]
            with open(target, "w", encoding="utf-8", newline="") as fh:
                fh.write(new)
            print(f"Injected sample table into {target} (between markers)")
            return
        print(f"WARNING: markers not found in {target}; writing table as whole file")
    with open(target, "w", encoding="utf-8", newline="") as fh:
        fh.write(table_md)
    print(f"Wrote markdown table to {target}")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", default=os.path.join(SCRIPT_DIR, "metadata_base.csv"),
                    help="Design metadata CSV with columns sample,Classification")
    ap.add_argument("--xengsort-dir", default=os.path.join(SCRIPT_DIR, "xengsort_out"),
                    help="Directory of per-sample xengsort logs (<sample>.txt)")
    ap.add_argument("--out", default=os.path.join(SCRIPT_DIR, "metadata_full.csv"),
                    help="Output metadata CSV (base columns + appended fractions)")
    ap.add_argument("--allow-missing", action="store_true",
                    help="Skip (with a warning) samples whose log is missing or "
                         "unparseable instead of failing")
    ap.add_argument("--cohorts", default=os.path.join(SCRIPT_DIR, "sample_cohorts.csv"),
                    help="Descriptive cohorts CSV (sample,cohort,environment,role) "
                         "for the --emit-markdown table; may include C2B")
    ap.add_argument("--emit-markdown", metavar="TARGET",
                    help="Also render the README sample table; TARGET is '-' "
                         "(stdout), or a file (injected between markers if present)")
    ap.add_argument("--markdown-only", action="store_true",
                    help="Skip the metadata CSV build; only emit the markdown table "
                         "(requires --emit-markdown)")
    args = ap.parse_args()

    if args.markdown_only and not args.emit_markdown:
        sys.exit("ERROR: --markdown-only requires --emit-markdown")

    if not os.path.isdir(args.xengsort_dir):
        sys.exit(f"ERROR: xengsort directory not found: {args.xengsort_dir}")

    if not args.markdown_only:
        build_csv(args)

    if args.emit_markdown:
        if not os.path.isfile(args.cohorts):
            sys.exit(f"ERROR: cohorts file not found: {args.cohorts}")
        with open(args.cohorts, newline="") as fh:
            reader = csv.DictReader(fh)
            if "sample" not in (reader.fieldnames or []):
                sys.exit(f"ERROR: cohorts file must have a 'sample' column: {args.cohorts}")
            cohorts = list(reader)
        table_md = render_markdown(cohorts, args.xengsort_dir, args.allow_missing)
        emit_markdown(args.emit_markdown, table_md)


if __name__ == "__main__":
    main()
